---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Lindsay Stall"
date: "1/31/23"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

```{r}
library(usethis)
use_git_config(user.name = "Lindsay Stall", 
               user.email = "stallm21@wfu.edu")
```

```{r}
staff <- read_csv("data/instructional-staff.csv")
```
```{r}
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))
```

```{r}
staff_long
```
### Exercise 1

```{r}
staff_long %>%
  ggplot(aes(x = year,
             y = value,
             group = faculty_type,
             color = faculty_type,)) +
  labs(
    x = "Years",
    y = "Faculty type",
    title = "Faculty Type by Year"
  ) +
  geom_line()
```

### Exercise 2

I would create 2 groups: one for part-time and one for full time to make the rates of employment between the groups easier to compare. 

### Exercise 3

```{r}
fisheries <- read_csv("data/fisheries.csv")
```
```{r}
fisheries_long <- fisheries %>%
  pivot_longer(cols = -country, names_to = "totals") %>%
  filter(totals %in% c("capture", "aquaculture")) %>%
  mutate(value = as.numeric(value))
```

```{r}
fisheries_long %>%
  filter(country %in% c("China", "Indonesia", "India", "United States", "Russia", "Peru", "Vietnam")) %>%
  ggplot(aes(fill = totals, y=value, x=country)) +
  labs(
    x = "Countries",
    y = "Tons of Fish",
    title = "Tons of Fish Produced by Top Ten Fish-Producing Countries"
  ) +
  geom_bar(position="stack", stat="identity")
```


### Exercise 3




### Exercise 3





### Exercise 3




### Exercise 3




### Exercise 3




### Exercise 3




### Exercise 3
